# resolution
# 決議
id:
  version:
    - date:
      title:
      _object: # 底下的子決議
        - _object
      _topic: # 對應的司改國是會議的主題
        - _topic
      _stakeholder: # 受影響的族群
        - _stakeholder
      _owner: # 主責單位
        - _owner
      _partner: # 配合單位
        - _partner
      _law:
        - _law
      _rule:
        - _rule
      _policy:
        - _policy
      milestone:
        - date:
          title:
          task:
            - title:
              description:
      note: # 自由發揮註解區

  status:
    - date: # 進入此狀態時間
      status: 草案規劃中 / 草案審議中 / 已成案 / 執行中 / 驗收中 / 已結案 / 放置中 / 已撤案 # 狀態
  progress:
    - date: # commit 日期
      type: 提出草案 / 修法 / 修行政命令 / 編預算 / 開會 / 辦活動 ... etc. # 進度類型
      title: # 進度條上的標題
      description:
      link: # 相關連結
        - title: 
          url: 
          type: # 連結類型

# object
# 子決議
id:
  version:
    - date:
      description:
      _mission: # 底下的子決議細項

      # 以下格式同決議
      _stakeholder:
      _owner:
      _partner:
      _law:
      _rule:
      _policy:
      milestone:
        - date:
          title:
          task:
            - title:
              description:
      note:
  status:
    - date: # 進入此狀態時間
      status: 草案規劃中 / 草案審議中 / 已成案 / 執行中 / 驗收中 / 已結案 / 放置中 / 已撤案 # 狀態
  progress:
    - date: # commit 日期
      type: 提出草案 / 修法 / 修行政命令 / 編預算 / 開會 / 辦活動 ... etc. # 進度類型
      title: # 進度條上的標題
      description:
      link: # 相關連結
        - title: 
          url: 
          type: # 連結類型

# mission
# 子決議細項
id:
  version:
    - date:
      description:

      # 以下格式同決議
      _stakeholder:
      _owner:
      _partner:
      _law:
      _rule:
      _policy:
      milestone:
        - date:
          title:
          task:
            - title:
              description:
      note:
  status:
    - date: # 進入此狀態時間
      status: 草案規劃中 / 草案審議中 / 已成案 / 執行中 / 驗收中 / 已結案 / 放置中 / 已撤案 # 狀態
  progress:
    - date: # commit 日期
      type: 提出草案 / 修法 / 修行政命令 / 編預算 / 開會 / 辦活動 ... etc. # 進度類型
      title: # 進度條上的標題
      description:
      link: # 相關連結
        - title: 
          url: 
          type: # 連結類型

# law
# 提案內容：修法
id:
  name: # 法規名稱
  description: # 修法方向
  paragraph: # 條
  subparagraph: # 項
  item: # 款
  old: # 原本條文內容
  new: # 修法後內容
  _legislator: # 負責提案的立委
    - _legislator
  link: # 相關連結
    - title: 
      url: 
      type: 

# rule
# 提案內容：修行政命令
id:
  name: # 行政命令名稱
  description: # 調整方向
  new: # 行政命令內容
  _office: # 發佈命令的機關
    - _office
  link: # 相關連結
    - title: 
      url: 
      type: 

# policy
# 提案內容：上層的政策
id:
  name: # 政策或計畫名稱
  description: # 施行方向
  _policy: # 上層的政策
    - _policy
  _office: # 負責政策的機關
    - _office
  link: # 相關連結
    - title: 
      url: 
      type: 

# office
# 單位或法人組織
id:
  name: # 單位名稱
  type: gov, ngo, com # 單位類別
  link: # 相關連結
    - title: 
      url: 
      type: 
  contact: # 聯絡窗口
    - name: 
      email: 
      phone: 

# topic
# 司改國是會議主題
id: name

# team
# 司改國是會議分組
id:
  name: 
  title: 
  _topic:
  description:
  _host:
  _committee:

# committee
# 司改國是會議委員
id:
  title:
  staff:
  _stakeholder:
  _office:

# stakeholder
# 受影響族群（資料來源：英國人神圖）
id:
  name_en: 
  description:

# system
# 司法體系（資料來源：英國人神圖）
id:
  description:
  activity:
  - name: 
    name_en: 
  group:
  - name: 體制內使用者
    name_en: internal users
    _stakeholder:
  - name: 體制外使用者
    name_en: external users
    _stakeholder:
