# resolution
# 決議
resolution_id:
  version:
    - date:
      title:
        - title
      description:
        - description
      _object: # 底下的子決議
        - _object
      _topic: # 對應的司改國是會議的主題
        - _topic

      # 以下三層決議共用欄位

      # 喬事階段會確定的
      _owner: # 主責單位
        - _owner
      _partner: # 配合單位
        - _partner

      # 填表階段會確定的
      background: # 背景 / 問題 / 成因 / 現況
        - paragraph
      feasibility: # 改革方向評估
        - paragraph
      plan:
        - paragraph
      hr:
        - paragraph
      _stakeholder: # 受影響的族群
        - _stakeholder
      impact:
        - paragraph
      law:
        - name: # 法規名稱
          type: # 修法類型
          description: # 修法方向
          paragraph: # 條
          subparagraph: # 項
          item: # 款
          old: # 原本條文內容
          new: # 修法後內容
          _legislator: # 負責提案的立委
            - _legislator
          link: # 相關連結
            - title: 
              url: 
              type: 
      rule:
        - name: # 行政命令名稱
          description: # 調整方向
          new: # 行政命令內容
          _office: # 發佈命令的機關
            - _office
          link: # 相關連結
            - title: 
              url: 
              type: 
      _period: # 期程，單選
      _meeting: # 司改國是會議編號，應提供選單
        - _meeting
      link:
        - title:
          description:
          url:
      keywords: # 司法關鍵字
        - keyword
      milestone: # 長期的才需要？寫在 plan 欄位裡面？（待確認）
        - date:
          title:
          task:
            - title:
              description:
      note: # 自由發揮註解區
      log:
        - date: date
          _log: 已送出
        - date: date
          _log: 已退回
        - date: date
          _log: 已上架

  status:
    - date: # 進入此狀態時間
      _status: # 狀態，單選
  progress:
    - date: # commit 日期
      _type: # 進度類型
      title: # 進度條上的標題
      description:
      link: # 相關連結
        - title: 
          url: 
          type: # 連結類型
      log:
        - date: date
          _log: 已送出
        - date: date
          _log: 已退回
        - date: date
          _log: 已上架
  updated: date

# object
# 子決議
object_id:
  version:
    - date:
      title:
      description:
      _mission: # 底下的子決議細項
      # 以下格式同決議

# mission
# 子決議細項
mission_id:
  version:
    - date:
      title:
      description:
      # 以下格式同決議

# log
log:
  - 已送出
  - 已退回
  - 已上架

# status
status:
  - 進行中
  - 已完成（納入常態業務）
  - 已完成

# period
period:
  - 待評估
  - 半年內
  - 一年內
  - 兩年內
  - 兩年以上

# progress
progress:
  - 開會
  - 送出請求
  - 收到回覆
  - 研擬修法
  - 提出方案
  - 編預算
  - 安排人力
  - 修法
  - 頒佈行政命令
  - 辦活動
  - 開記者會
  - 其他

# policy
policy:
  - 無所屬政策
  - 內政部 OOO 年 OOO 計畫
  - 法務部 OOO 年 OOO 計畫

# policy
# 提案內容：上層的政策
policy_id:
  name: # 政策或計畫名稱
  description: # 施行方向
  _policy: # 上層的政策
    - _policy
  _office: # 負責政策的機關
    - _office
  link: # 相關連結
    - title: 
      url: 
      type: 

# office
# 單位或法人組織
office_id:
  name: # 單位名稱
  type: gov, ngo, com # 單位類別
  link: # 相關連結
    - title: 
      url: 
      type: 
  contact: # 聯絡窗口
    - name: 
      email: 
      phone: 

# topic
# 司改國是會議主題
topic_id:
  title:
  _topic:
    - _topic
  _agenda:
    - _agenda

# agenda
# 司改國是會議討論項目
agenda_id:
  title:
  description:
    - paragraph
  _meeting:
    - _meeting

# team
# 司改國是會議分組
team_id:
  name: 
  title: 
  _topic:
  description:
  _host:
  _committee:

# committee
# 司改國是會議委員
committee_id:
  title:
  staff:
  _stakeholder:
  _office:

# stakeholder
# 受影響族群（資料來源：英國人神圖）
stakeholder_id:
  name_en: 
  description:

# system
# 司法體系（資料來源：英國人神圖）
system_id:
  description:
  activity:
  - name: 
    name_en: 
  group:
  - name: 體制內使用者
    name_en: internal users
    _stakeholder:
  - name: 體制外使用者
    name_en: external users
    _stakeholder:
