# resolution
id:
  title: 
  _object:
  _topic:

  _stakeholder:

  _owner:
  _partner:
  note:
  log:
    - type: meeting, training, proposal, law_reform, rule_reform, get_budget, other
      title: 
      description:
      date: 
      link:
        - title: 
          url: 
          type: 

# object
id:
  description:
  _mission:

  _stakeholder:

  _owner:
  _partner:
  note:
  log:
    - type: meeting, training, proposal, law_reform, rule_reform, get_budget, other
      title: 
      description:
      date: 
      link:
        - title: 
          url: 
          type: 

# mission
id:
  description:

  _stakeholder:

  _owner:
  _partner:
  note:
  log:
    - type: meeting, training, proposal, law_reform, rule_reform, get_budget, other
      title: 
      description:
      date: 
      link:
        - title: 
          url: 
          type: 

# meeting
id:
  name:
  description:
  date:
  record:
    - name:
      url:

# training
id:
  name:
  description:
  date:
  record:
    - name:
      url:

# proposal
id:
  name:
  description:
  date:
  milestone:
    - name:
      date:
      task:
        - name:
          description:
  status:
  _law_reform:
    - _law_reform
  _rule_reform:
    - _rule_reform
  _policy:
    - _policy

# law_reform
id:
  name:
  description:
  date:
  paragraph:
  subparagraph:
  item:
  old:
  new:

# rule_reform
id:
  name:
  description:
  date:
  paragraph:
  subparagraph:
  item:
  old:
  new:

# get_budget
id:
  name:
  description:

# policy
id:
  description:
  url:
  _policy:
  _office: 
    - _office

# office
id:
  type: gov, ngo
  contact: 
    - name: 
      email: 
      phone: 

# topic
id: name

# team
id:
  name: 
  title: 
  _topic:
  description:
  _host:
  _committee:

# committee

id:
  title:
  staff:
  _stakeholder:
  _office:

# stakeholder
id:
  name_en: 
  description:

# system
id:
  description:
  activity:
  - name: 
    name_en: 
  group:
  - name: 體制內使用者
    name_en: internal users
    _stakeholder:
  - name: 體制外使用者
    name_en: external users
    _stakeholder:
