# resolution
id:
name:
description:
subresolution:
  - _subresolution
team:
  - _team

# team
id:
name:
description:
host:
member:

# subresolution
id:
name:
description:
owner:
  - _office
partner:
  - _office
stakeholder_group:
  - _group
stakeholder_org:
  - _org
proposal: 
    - _proposal
log:
  - type: meeting, training, proposal, law_reform, rule_reform, get_budget, other
    id: _id

# meeting
id:
name:
description:
date:
record:
  - name:
    url:

# training
id:
name:
description:
date:
record:
  - name:
    url:

# proposal
id:
name:
description:
date:
milestone:
  - name:
    date:
    task:
      - name:
        description:
status:
law_reform:
  - _law_reform
rule_reform:
  - _rule_reform
policy:
  - _policy

# law_reform
id:
name:
description:
date:
paragraph:
subparagraph:
item:
old:
new:

# rule_reform
id:
name:
description:
date:
paragraph:
subparagraph:
item:
old:
new:

# get_budget
id:
name:
description:

# policy
id:
name:
description:
url:
office: 
  - office

# office
id:
name:
description:
contact: 
  - name: 
    email: 
    tel: 

# stakeholder_category
id:
name:
description:
stakeholder_group:
  - _stakeholder_group

# stakeholder_group
id:
name:
description:

# stakeholder_org
id:
name:
description:
