# resolution
# 決議
id:
  title: 
  _object: # 底下的子決議
  _topic: # 對應的司改國是會議的主題

  _stakeholder: # 受影響的族群
  _owner: # 主責單位
  _partner: # 配合單位
  note: # 自由發揮註解區
  log: # 進度表
    - type: 提出草案 / 修法 / 修行政命令 / 編預算 / 開會 / 辦活動 ... etc.
      title: 
      description:
      date: # commit 日期
      link: # 相關連結
        - title: 
          url: 
          type: 

# object
# 子決議
id:
  description:
  _mission: # 底下的子決議細項

  # 以下格式同決議
  _stakeholder:
  _owner:
  _partner:
  note:
  log:
    - type: 
      title: 
      description:
      date: 
      link:
        - title: 
          url: 
          type: 

# mission
# 子決議細項
id:
  description:

  # 以下格式同決議
  _stakeholder:
  _owner:
  _partner:
  note:
  log:
    - type: 
      title: 
      description:
      date: 
      link:
        - title: 
          url: 
          type: 

# meeting
# 進度：會議
id:
  name:
  description:
  date:
  record:
    - name:
      url:

# training
# 進度：教育訓練
id:
  name:
  description:
  date:
  record:
    - name:
      url:

# proposal
# 進度：提案
id:
  name:
  description:
  date:
  milestone:
    - name:
      date:
      task:
        - name:
          description:
  status:
  _law_reform:
    - _law_reform
  _rule_reform:
    - _rule_reform
  _policy:
    - _policy

# law_reform
# 進度：修法
id:
  name:
  description:
  date:
  paragraph:
  subparagraph:
  item:
  old:
  new:

# rule_reform
# 進度：修行政命令
id:
  name:
  description:
  date:
  paragraph:
  subparagraph:
  item:
  old:
  new:

# get_budget
# 進度：編預算
id:
  name:
  description:

# policy
# 上層的政策
id:
  description:
  url:
  _policy:
  _office: 
    - _office

# office
# 單位或法人組織
id:
  type: gov, ngo
  contact: 
    - name: 
      email: 
      phone: 

# topic
# 司改國是會議主題
id: name

# team
# 司改國是會議分組
id:
  name: 
  title: 
  _topic:
  description:
  _host:
  _committee:

# committee
# 司改國是會議委員
id:
  title:
  staff:
  _stakeholder:
  _office:

# stakeholder
# 受影響族群（資料來源：英國人神圖）
id:
  name_en: 
  description:

# system
# 司法體系（資料來源：英國人神圖）
id:
  description:
  activity:
  - name: 
    name_en: 
  group:
  - name: 體制內使用者
    name_en: internal users
    _stakeholder:
  - name: 體制外使用者
    name_en: external users
    _stakeholder:
